title: Unicorn's Blog
markdown: kramdown

# for atom feed
author:
  name: Unicorn

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-scholar

collections_dir: all_collections
collections:
  posts:
    output: true

scholar:
  style: assets/ieee.csl
  bibliography: '*.bib'

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "sync-csie.bat"]
